// <auto-generated />
namespace _5StarWifi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedMovieRating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMovieRating));
        
        string IMigrationMetadata.Id
        {
            get { return "202108230333427_AddedMovieRating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
